import { AuthProvider } from "@/context/Auth";
import { getNextAuthSession } from "@/libs/next-auth";
import { Theme } from "@radix-ui/themes";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { PropsWithChildren } from "react";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({ children }: PropsWithChildren) => {
  const session = await getNextAuthSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider session={session}>
          <Theme>{children}</Theme>
        </AuthProvider>
      </body>
    </html>
  );
};

export default RootLayout;
