import { getNextAuthSession } from "@/libs/next-auth";
import {
  SupportedLanguages,
  getI18nLocale,
  i18nDefaultLanguage,
} from "@/libs/next-intl";
import "@/styles/main.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { notFound } from "next/navigation";
import { PropsWithChildren } from "react";
import { RootLayoutProviders } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const localeHandler = async (locale: SupportedLanguages) => {
  try {
    return await getI18nLocale(locale);
  } catch (error) {
    notFound();
  }
};

const RootLayout = async ({ children }: PropsWithChildren) => {
  const session = await getNextAuthSession();
  const messages = await localeHandler("en");

  return (
    <html lang={i18nDefaultLanguage}>
      <body className={inter.className}>
        <RootLayoutProviders
          session={session}
          locale={i18nDefaultLanguage}
          messages={messages}
        >
          {children}
        </RootLayoutProviders>
      </body>
    </html>
  );
};

export default RootLayout;
